Feat/SPN-1 add user module
syntaxnexus/spendora pull request #4
Opened 2023-09-29 23:15 UTC by aelshinawy

Addresses ticket no **[SPN-1](https://syntaxnexus.youtrack.cloud/issue/SPN-1) Create User Module**

2023-10-02 22:39 UTC, Riolite requested changes

2023-10-02 22:39 UTC, Riolite commented on backend/build.gradle.kts
> +	implementation("io.vavr:vavr-jackson:0.10.3")
Please make this version configurable. You can use vavrVersion and set it to 0.10.3

2023-10-02 22:39 UTC, Riolite commented on backend/src/main/java/com/syntaxnexus/spendora/user/UserService.java
> +        return Try.of(userRepository::findAll);
```suggestion
        return Try.of(userRepository::findAll).orElse(Collections.emptyList());

```

2023-10-02 22:39 UTC, Riolite commented on backend/src/main/java/com/syntaxnexus/spendora/user/UserService.java
> +        return Try.of(userRepository::findAll);
You can use orElse here if you want to handle failure with an emptyList.

2023-10-02 22:39 UTC, Riolite commented on backend/src/main/java/com/syntaxnexus/spendora/user/UserController.java
> +        return Try.of(()-> userService.findById(userId).get())
No need to call Try.get() and wrap it in a Try here.

2023-10-03 10:55 UTC, aelshinawy commented on backend/src/main/java/com/syntaxnexus/spendora/user/UserService.java
> +        return Try.of(userRepository::findAll);
Can't because it violates the function return value

2023-10-03 16:35 UTC, Riolite approved these changes

2023-10-03 16:36 UTC, Riolite commented
Good job!!

2023-10-03 20:01 UTC, merged